on:
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get time
        run: |
          echo "time=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      - name: Download adgh filter files
        run: |
          mkdir -p publish
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt -O ./publish/AdGuard-DNS-filter.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt -O ./publish/AdAway-Default-Blocklist.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt -O ./publish/OISD-Blocklist-Big.txt
          wget https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt -O ./publish/CHN-AdRules-DNS-List.txt
          wget https://easylist.to/easylist/easyprivacy.txt -O ./publish/EasyPrivacy.txt
      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false
      - name: Release and upload assets
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: latest
          tag: latest
          file_glob: true
          overwrite: true
          file: ./publish/*
          body: ${{ env.time }}
      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@latest/${file}"
          done
      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1